<?php

namespace JYG\RevestimientosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
	public function AllOrdenById(){
		$query = $this->getEntityManager()
			->createQuery('SELECT u
				FROM JYGRevestimientosBundle:Cliente u
				ORDER BY u.id DESC');
		$result = $query->getResult();

		return $result;
	}
}
