<?php

namespace JYG\RevestimientosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompraMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompraMaterialRepository extends EntityRepository
{
}
