<?php

namespace JYG\RevestimientosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaRepository extends EntityRepository
{
	public function ObtenerporAgregado(){
		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM JYGRevestimientosBundle:Galeria u 
				ORDER BY u.id DESC');
		$result = $query->getResult();
        
        return $result;
	}
}
