<?php

namespace JYG\RevestimientosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCompraRepository extends EntityRepository
{
}
