<?php

namespace JYG\RevestimientosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
	public function findNumVenta($a){
		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM JYGRevestimientosBundle:Item u 
				WHERE u.venta= :num');
		$query->setParameter('num', $a);
		$result = $query->getResult();
        
        return $result;
	}

	public function AllOrdenById(){
		$query = $this->getEntityManager()
			->createQuery('SELECT u
				FROM JYGRevestimientosBundle:Item u
				ORDER BY u.id DESC');
		$result = $query->getResult();

		return $result;
	}
}
