<?php

namespace JYG\RevestimientosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends EntityRepository
{
	public function UltimosTresAgregados(){
		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM JYGRevestimientosBundle:Material u 
				ORDER BY u.id DESC')
				->setMaxResults(3);
		$result = $query->getResult();
        
        return $result;
	}

	public function ObtenerporAgregado(){
		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM JYGRevestimientosBundle:Material u 
				ORDER BY u.id DESC');
		$result = $query->getResult();
        
        return $result;
	}
}
