<?php

namespace JYG\RevestimientosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaRepository extends EntityRepository
{
	public function BuscarPorRif($rif){
		$query = $this->getEntityManager()
				->createQuery('SELECT u 
				FROM JYGRevestimientosBundle:Cliente u 
				WHERE u.rif = :rif');
		$query->setParameter('rif', $rif);
		$result = $query->getResult();
        
        return $result;
	}

	public function AllOrdenById(){
		$query = $this->getEntityManager()
			->createQuery('SELECT u
				FROM JYGRevestimientosBundle:Venta u
				ORDER BY u.id DESC');
		$result = $query->getResult();

		return $result;
	}
}
